name: Functions Generate
"on": push
jobs:
  generate:
    runs-on: ubuntu-24.04
    steps:
      - run: printenv | grep 'FN_'
        env:
          FN_FORMAT: ${{ format('{0}, {1}!', 'Hello',  'world') }}
          FN_JOIN: ${{ join(github.event.*.html_url , ', ') }}
