name: Literals
"on": push
jobs:
  print:
    runs-on: ubuntu-24.04
    steps:
      - run: printenv | grep 'LITERAL_'
        env:
          LITERAL_NUMBER: ${{ 42 }}
          LITERAL_BOOLEAN: ${{ true }}
          LITERAL_NULL: ${{ null}}
          LITERAL_STRING: ${{ 'Hello' }}
          LITERAL_OMIT_STRING: World
