name: Manual
"on":
  workflow_dispatch:
    inputs:
      greeting:
        type: string
        description: "Greeting message"
        required: true
        default: "Hello"

jobs:
  run:
    runs-on: ubuntu-24.04
    steps:
      - run: echo "${{ github.event.inputs.greeting }}"
