name: Repository Secrets
"on": push
jobs:
  run:
    runs-on: ubuntu-24.04
    env:
      PASSWORD: ${{ secrets.PASSWORD}}
    steps:
      # マスキングされたままの値
      - run: echo "${PASSWORD}"
      # マスキングを解除した値を表示
      # 1文字目を取り出す: ${PASSWORD:0:1}
      # 2文字目以降を取り出す: ${PASSWORD#?}
      - run: echo "${PASSWORD:0:1} ${PASSWORD#?}"
